pipeline {
    agent any
    environment {
        	 cluster = "vproappprod"
        	service = "vproappptask-stack-prod"'
    }

    stages {
        stage('Deploy to Prod ecs') {
          steps {
        withAWS(credentials: 'awscreds', region: 'us-east-1') {
          sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
        }
      }
     }

    }
}
