pipeline {
    agent any
    tools {
        maven "MAVEN3.9.9"
        jdk "JDK17"
    }
    
    environment {
        	SNAP_REPO = 'vprofile-snapshot'
		NEXUS_USER = 'admin'
		NEXUS_PASS = 'admin'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vpro-maven-central'
		NEXUSIP = '172.31.94.37'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vpro-maven-group'
       		NEXUS_LOGIN = 'nexuslogin'
	    	SONARSERVER = 'sonarserver'
	    	SONARSCANNER = 'sonarscanner'
	    	registryCredential = 'ecr:us-east-1:awscreds'
	    	appRegistry = '905418436473.dkr.ecr.us-east-1.amazonaws.com/vprofileappimage'
		vprofileRegistry = 'https://905418436473.dkr.ecr.us-east-1.amazonaws.com'
		cluster = "vproappstaging"
        	service = "serivce name post create"

    }

    stages {
        stage('Build'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
		 post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
	stage('TEST'){
            steps {
                sh 'mvn -s settings.xml test'
            }
        }
	stage('Checkstyle Analysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }
	     stage('CODE ANALYSIS with SONARQUBE') {
          
		  environment {
             scannerHome = tool "${SONARSCANNER}"
          }

          steps {
            withSonarQubeEnv("${SONARSERVER}") {
               sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
            }
	  }
	}
	stage('QUALITY GATE'){
            steps {
                timeout(time: 1, unit: 'HOURS') {
               waitForQualityGate abortPipeline: true
            }
            }
        } 
	    stage("UploadArtifact")
{
 steps
 {
	nexusArtifactUploader(
	 nexusVersion: 'nexus3',
	 protocol: 'http',
	 nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
	 groupId: 'QA',
	 version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
	 repository: "${RELEASE_REPO}",
	 credentialsId: "${NEXUS_LOGIN}",
	 artifacts: [
	  [artifactId: 'vproapp',
	   classifier: '',
	   file: 'target/vprofile-v2.war',
	   type: 'war']
	 ]
	)
 }
}
	    stage('Build App Image') {
            steps {
                script {
                    dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")    // it is in format name, tagnumber, path_of_dockerfile
                }
            }
        }
        
        stage('Upload App Image') {
          steps{
            script {
              docker.withRegistry( vprofileRegistry, registryCredential )           //it is in format ecr url followed by ecr credentials
		    {                   
                dockerImage.push("$BUILD_NUMBER")
                dockerImage.push('latest')
              }
            }
          }
        }
stage('Deploy to staging ECS') {
            steps {
    //            withAWS(credentials: 'awscreds', region: 'us-east-1') {
      //              sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'                         //this will pull new image that is pushed to ecr to update ecs cluster
                } 
            }
        }

    }
}
